### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by klawr** [deeplex/walter#14]
*Created by: klawr*

**Problem Description**
The testing is done experimentally until now.
This is not acceptable and has to be updated asap.

**Proposed Solution**
Use xUnit to Test at least the creation of every object.
Doing this a lot of code has to be refactored into being testible.
After that all functions that are worked on should be extended by actual unit tests.
If some classes are skipped a short description why should be added, so that after future discussions they can be covered, too.

**Alternavitve Solution**
Actively Skip some tests to get to work faster.
All skipped tests should be implemented when the respective function is altered in any way.

**Additional Context**
The testing should be done for all backend projects.
Testing frontend will be another issue.

# Tasks:
Add tests for the following projects (including Skips to get back to work...):
 - [ ] Deeplex.Saverwalter.CLI (There are no functions to test 🙂)
 - [ ] Deeplex.Saverwalter.Model
 - [ ] Deeplex.Saverwalter.Print
 - [ ] Deeplex.Saverwalter.Services
 - [ ] Deeplex.Saverwalter.WebApi
 - [ ] Deeplex.Saverwalter.WebApi/svelte
 
 Skip all tests at first which require extra work. Then reiterate creating mocks on the way to be able to remove some of those skips.
Create a project for missing tests describing why they are difficult.
