### ISSUE TITLE
Remove technical debt

### ISSUE THREAD

**Issue by klawr** [deeplex/walter#42]
*Created by: klawr*

**Problem Description**
There are a lot of little mistakes which need to be addressed. Most of them are technical debt which should be removed right 
Before rigorous testing can commence these problems should be addressed to avoid refactoring tests, too.

**Proposed Solution**
 
- [x] List all Umlagen in Betriebskostenabrechnung (show 0€ for missing ones)
- [x] If filter is shorted, lists are not updated accordingly
- [x] Fix Titles...
- [x] Fix update of Ansprechpartner
- [x] Fix Zaehler (Might be a bigger issue)
- [x] Rename BetriebskostenRechnungenListEntry to BetriebskostenRechnungenListViewModelEntry
- [x] VertragEntry seems to be wrong (see VertragListViewModel base) will be handled in #47 
- [x] No way to create JuristischePerson
- [x] Fix ZaehlerDetailViewModel Lists
- [x] MietenListControl.AddMiete (VertragDetailViewPage)
- [x] MietMinderungListControl.AddMiete (VertragDetailViewPage)
- [x] Fix Mieter (May need an extra ViewPage?)
- [x] JuristischePerson AddMitglied (May use same ViewPage as Mieter?) handled in #48 
- [x] NatuerlichePerson and JuristischePerson AddJuristischePerson (May use same ViewPage as Mieter?) handled in #48 
- [x] Vertrag => UmlageList
- [x] Add MetaService class (Replace by simpleInjector #43 )
- [x] VertragViewModels (Miete, VertragVersion... ?) will be handled in #47
- [x] No Detail in Natuerliche und JuristischePersonViewModel
- [x] Set Private Member in Interfaces (C#10 upgrade necessary) (Private Entities happened to be only generic. Fixed in #45 by using abstract classes)
- [x] Redo the folder structure
- [x] Fix Adresse
- [x] Remove VertragListViewModelMiete
- [x] Move Files from Views to Service
- [x] Remove isMieter, isHandwerker, isVermieter (Annoying and not so helpful tbh)
- [x] Still called MietMinderung in Model (rename to Mietminderung)
- [x] 5% of AllgemeinStrom are currently not subtracted from Betriebskostenrechnung
- [x] Can't add or remove Versionen (may use same logic as Mieten) will be handled in #47
